/**
 * CoSlate core types.
 *
 * The scene is the single source of truth. Everything else in CoSlate —
 * renderers, tools, exporters, future collaboration or AI clients — is a
 * projection of, or a producer of commands against, this model.
 *
 * The whole scene is plain JSON: no class instances, no functions, no DOM
 * handles, no cyclic references. That is what makes serialization, patching and
 * (later) transport trivial.
 */

/** A stable, opaque identifier. Generated by {@link newId}. */
export type Id = string;

/**
 * Every object type CoSlate v1 understands.
 *
 * The `namespace.name` shape is deliberate: it leaves room for third-party
 * object types (`acme.chart`) without a schema change, and it keeps the
 * built-in whiteboard primitives grouped.
 */
export type ObjectType =
  | 'shape.rect'
  | 'shape.ellipse'
  | 'shape.line'
  | 'shape.arrow'
  | 'shape.text'
  | 'freehand.stroke';

/** Colour values are plain CSS colour strings, or `null` for "no paint". */
export type Paint = string | null;

export interface RectData {
  fill: Paint;
  stroke: Paint;
  strokeWidth: number;
  cornerRadius: number;
}

export interface EllipseData {
  fill: Paint;
  stroke: Paint;
  strokeWidth: number;
}

/**
 * A polyline. `points` is a flat `[x0, y0, x1, y1, ...]` list in the object's
 * *local* coordinate space, whose origin is the object's top-left corner
 * (`x`, `y`) and whose extent equals `width` x `height` before `scaleX` /
 * `scaleY`. Keeping points local is what lets resize be a pure scale.
 */
export interface LineData {
  points: number[];
  stroke: Paint;
  strokeWidth: number;
}

export interface ArrowData extends LineData {
  pointerLength: number;
  pointerWidth: number;
}

export interface TextData {
  text: string;
  fontFamily: string;
  fontSize: number;
  fill: Paint;
  align: 'left' | 'center' | 'right';
}

/** Freehand ink. `points` are local-space, exactly like {@link LineData}. */
export interface StrokeData {
  points: number[];
  stroke: Paint;
  strokeWidth: number;
}

/** Maps an object type to the payload it carries in `SceneObject.data`. */
export interface ObjectDataMap {
  'shape.rect': RectData;
  'shape.ellipse': EllipseData;
  'shape.line': LineData;
  'shape.arrow': ArrowData;
  'shape.text': TextData;
  'freehand.stroke': StrokeData;
}

/** Convenience alias for the union of all possible object payloads. */
export type ObjectData = ObjectDataMap[ObjectType];

export interface Bounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Point {
  x: number;
  y: number;
}

export interface Size {
  width: number;
  height: number;
}

/**
 * Camera. `x`/`y` are the *world* coordinates that sit at the top-left corner of
 * the viewport; `scale` is screen pixels per world unit.
 *
 *   screen = (world - viewport.xy) * scale
 */
export interface Viewport {
  x: number;
  y: number;
  scale: number;
}

/**
 * A single object in the scene.
 *
 * Geometry is transform-based: `x`/`y` place the object, `width`/`height` are
 * its untransformed box, and `rotation` / `scaleX` / `scaleY` compose around the
 * object's top-left corner. Renderers must not flatten these into baked
 * coordinates — that destroys round-tripping.
 */
export interface SceneObject {
  id: Id;
  type: ObjectType;
  /** Per-object schema version, so a single object can migrate independently. */
  version: number;
  x: number;
  y: number;
  width: number;
  height: number;
  /** Degrees, clockwise, around the object's top-left corner. */
  rotation: number;
  scaleX: number;
  scaleY: number;
  /** Paint order. Kept in sync with `Scene.order`; `order` wins. */
  z: number;
  visible: boolean;
  locked: boolean;
  /** Reserved for future grouping. v1 never sets it to a non-null value. */
  parentId?: Id | null;
  data: ObjectData;
  /**
   * Deliberately free-form. `meta` is the extension hatch: AI provenance,
   * comments, authorship, plugin scratch space. Adding keys here never requires
   * a format version bump, so features can ship without a migration.
   */
  meta?: Record<string, unknown>;
}

/** A {@link SceneObject} narrowed to one concrete type. */
export type SceneObjectOf<T extends ObjectType> = SceneObject & {
  type: T;
  data: ObjectDataMap[T];
};

/** Narrowing helper; the only sanctioned way to reach a typed `data`. */
export function isObjectOfType<T extends ObjectType>(
  object: SceneObject,
  type: T,
): object is SceneObjectOf<T> {
  return object.type === type;
}

/**
 * The document format.
 *
 * `format` + `version` are the serialization contract; see `serialize.ts` and
 * ARCHITECTURE.md. `objects` is a lookup table keyed by id and `order` is the
 * authoritative paint order, which keeps reordering O(n) instead of a `z`
 * rewrite across the whole document.
 *
 * **The camera is not here.** It used to be `Scene.viewport`, which meant a
 * shared document carried someone's view of it: broadcast a scene and every
 * participant got dragged to the publisher's pan position, and a saved baseline
 * recorded whose camera happened to be current. The camera is per-user view
 * state, so it lives in the editor (and in whatever a host persists for its own
 * user) — never in the document. Version 2 dropped the field; see the migration
 * in `serialize.ts`.
 */
export interface Scene {
  format: 'coslate/scene';
  version: 2;
  objects: Record<Id, SceneObject>;
  order: Id[];
  /** Document-level free-form metadata, same rationale as `SceneObject.meta`. */
  meta?: Record<string, unknown>;
}

export const SCENE_FORMAT = 'coslate/scene' as const;
export const SCENE_VERSION = 2 as const;

/** A blank document. */
export function createEmptyScene(): Scene {
  return { format: SCENE_FORMAT, version: SCENE_VERSION, objects: {}, order: [] };
}

/** Default geometry/factory for a new object of a given type. */
export function defaultData<T extends ObjectType>(type: T): ObjectDataMap[T];
export function defaultData(type: ObjectType): ObjectData {
  switch (type) {
    case 'shape.rect':
      return { fill: null, stroke: '#e6e6e6', strokeWidth: 2, cornerRadius: 0 };
    case 'shape.ellipse':
      return { fill: null, stroke: '#e6e6e6', strokeWidth: 2 };
    case 'shape.line':
      return { points: [0, 0, 0, 0], stroke: '#e6e6e6', strokeWidth: 2 };
    case 'shape.arrow':
      return {
        points: [0, 0, 0, 0],
        stroke: '#e6e6e6',
        strokeWidth: 2,
        pointerLength: 12,
        pointerWidth: 10,
      };
    case 'shape.text':
      return {
        text: '',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 20,
        fill: '#e6e6e6',
        align: 'left',
      };
    case 'freehand.stroke':
      return { points: [], stroke: '#e6e6e6', strokeWidth: 2 };
    default: {
      const never: never = type;
      throw new Error(`CoSlate: unknown object type ${String(never)}`);
    }
  }
}

export const OBJECT_TYPES: readonly ObjectType[] = [
  'shape.rect',
  'shape.ellipse',
  'shape.line',
  'shape.arrow',
  'shape.text',
  'freehand.stroke',
];
